image: golang:1.14

stages:
- build

cache:
  key: yup
  paths:
  - /go/pkg

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"

before_script:
- go mod download

lint:
  stage: build
  image: golangci/golangci-lint:v1.27.0
  script:
  - golangci-lint run -v

build:
  stage: build
  variables:
    CGO_ENABLED: "0"
  script:
  - go build -o netlify-deployer
